name: 'Check spelling'
description: 'Spell check commits'
author: 'briandfoy'
branding:
  icon: 'edit-3'
  color: 'red'
inputs:
  debug:
    description: 'Turn on more information'
    default: 0
runs:
  using: 'composite'
  steps:
    - run: |
        perl ${{ github.action_path }}/master_controller.pl
      shell: bash
      env:
        INPUT_DEBUG: ${{ inputs.debug }}
